config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :heat_ratings, only: [:edit, :update, :index]
  resources :forecasts, only: [:new, :create, :index]

  root to: 'forecasts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forecast.rb
class Forecast < ApplicationRecord
  ACCEPTED_COUNTRIES = ['UK'].freeze

  validates :postcode, presence: true
  validates_with UkPostcodeValidator
  before_create :perform_forecast

  def heat_rating
    ratings = HeatRating.where('? BETWEEN min_temp AND max_temp', self.max_temp)
    return unless ratings.present?

    ratings.first.name
  end

  private

  def perform_forecast
    begin
      forecast_data = WeatherServices::Forecaster.new(self.postcode).perform
      self.country = forecast_data.dig('location', 'country') || ''
      validate_country!

      forecastday = forecast_data.dig('forecast', 'forecastday') || [{}]
      self.max_temp = forecastday.first.dig('day', 'maxtemp_c')
    rescue WeatherServicesError => e
      self.errors.add(:service, "error: #{e}")
      throw(:abort)
    end
  end

  def validate_country!
    unless ACCEPTED_COUNTRIES.include?(self.country)
      self.errors.add(:postcode, "country is not accepted")
      throw(:abort)
    end
  end
end

app/models/heat_rating.rb
class HeatRating < ApplicationRecord
  MINIMUM_VALID_TEMPERATURE = -100.freeze
  MAXIMUM_VALID_TEMPERATURE = 100.freeze

  validates :min_temp, numericality: {
    greater_than_or_equal_to: MINIMUM_VALID_TEMPERATURE,
    less_than_or_equal_to: MAXIMUM_VALID_TEMPERATURE,
    less_than: Proc.new {|record| record.max_temp }
  }
  validates :max_temp, numericality: {
    greater_than_or_equal_to: MINIMUM_VALID_TEMPERATURE,
    less_than_or_equal_to: MAXIMUM_VALID_TEMPERATURE,
    greater_than: Proc.new {|record| record.min_temp }
  }
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def index
    @forecasts = Forecast.all
  end

  def new
    @forecast = Forecast.new
  end

  def create
    @forecast = Forecast.new(forecast_params)

    if @forecast.save
      redirect_to forecasts_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def forecast_params
    params.require(:forecast).permit(:postcode)
  end
end

app/controllers/heat_ratings_controller.rb
class HeatRatingsController < ApplicationController
  before_action :set_heat_rating, except: :index

  def index
    @heat_ratings = HeatRating.all.order(:min_temp)
  end

  def edit
  end

  def update
    if @heat_rating.update(heat_rating_params)
      redirect_to edit_heat_rating_url(@heat_rating)
    else
      render :edit
    end
  end

  private

  def set_heat_rating
    @heat_rating = HeatRating.find(params[:id])
  end

  def heat_rating_params
    params.require(:heat_rating).permit(:min_temp, :max_temp, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/helpers/heat_ratings_helper.rb
module HeatRatingsHelper
end

app/views/forecasts/index.html.erb
<h1>Forecasts</h1>

<% if @forecasts.present? %>
  <table>
    <thead>
      <tr>
        <th>Postcode</th>
        <th>Rating</th>
      </tr>
    </thead>

    <tbody>
      <% @forecasts.each do |forecast| %>
        <tr>
          <td><%= forecast.postcode %></td>
          <td><%= forecast.heat_rating %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/forecasts/new.html.erb
<h1>New forecast</h1>

<%= form_with(model: @forecast, local: true) do |form| %>
  <% if @forecast.errors.any? %>
    <p>Failed to save...</p>

    <ul>
      <% @forecast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :postcode %>
    <%= form.text_field :postcode, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/heat_ratings/edit.html.erb
<h1>Edit <%= @heat_rating.name %> </h1>

<%= form_with(model: @heat_rating, local: true) do |form| %>
  <% if @heat_rating.errors.any? %>
    <p>Failed to save...</p>

    <ul>
      <% @heat_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label 'Minimum temperature' %>
    <%= form.number_field :min_temp %>
  </div>

  <div>
    <%= form.label 'Maximum temperature' %>
    <%= form.number_field :max_temp %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/heat_ratings/index.html.erb
<h1>Heat Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Minimum temp</th>
      <th>Maximum temp</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @heat_ratings.each do |heat_rating| %>
      <tr>
        <td><%= heat_rating.name %></td>
        <td><%= heat_rating.min_temp %></td>
        <td><%= heat_rating.max_temp %></td>
        <td><%= link_to 'Edit', edit_heat_rating_path(heat_rating) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Home', root_url %>
      <%= link_to 'Manage heat ranges', heat_ratings_url %>
      <%= link_to 'Get a forecast', new_forecast_url %>
    </nav>

    <%= yield %>
  </body>
</html>